version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: spring
    networks:
      - spring

  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: spring
    networks:
      - spring

  redis:
    container_name: redis
      image: redis:latest
      ports:
          - 6379:6379
      restart: always
#      command: redis-server /usr/local/conf/redis.conf
      command: redis-server ./redis.conf
      networks:
        - spring

networks:
  spring: